#!/bin/sh

version=3-2

resources="paintown-$version.app/Contents/Resources"

cp paintown-static paintown-$version
rm -rf paintown-$version.app
fixbundle paintown-$version -v $version -V "Paintown $version"
cp scripts.zip $resources
cp editor/editor.jar $resources
cp editor/run.sh $resources
(cd $resources; svn export https://paintown.svn.sf.net/svnroot/paintown/data)
buildDMG.pl -compressionLevel 9 -dmgName paintown-$version paintown-$version.app/
echo "Created paintown-$version.dmg"
ls -l paintown-$version.dmg
