#!/bin/bash -e

DOCKER_PS3_BUILD_IMAGE=paintown-ps3-build
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build -t ${DOCKER_PS3_BUILD_IMAGE} -f docker/Dockerfile.ps3 .
docker run --rm -iv${PWD}:/paintown-bin -w /paintown-bin ${DOCKER_PS3_BUILD_IMAGE} sh -s <<EOF
make ps3
cp build-ps3/paintown paintown-ps3.elf
EOF
echo "
To run you will need a CFW [custom firmware] or system that can boot unsigned applications
"

ls -l paintown-ps3.elf
file paintown-ps3.elf
echo "Here is the executable. To run you need to package as a pkg file"
