#!/bin/bash -e
# Build bins for GC, WII, WIIU and/or SWITCH

PPC_IMAGE=paintown-dkp-ppc-build
ARM_IMAGE=paintown-dkp-arm-build
A64_IMAGE=paintown-dkp-a64-build
BUILD_DIR=/build
GAMECUBE_BUILD_DIR=${BUILD_DIR}/build-gamecube
WII_BUILD_DIR=${BUILD_DIR}/build-wii
WIIU_BUILD_DIR=${BUILD_DIR}/build-wiiu
DS_BUILD_DIR=${BUILD_DIR}/build-3ds
SWITCH_BUILD_DIR=${BUILD_DIR}/build-switch
mkdir -p ${PWD}/dkp-bin

echo "Building GameCube, WII and WII-U..."
docker build -t ${PPC_IMAGE} -f docker/Dockerfile.dkp.ppc .
docker run --rm -iv${PWD}:/paintown-bin ${PPC_IMAGE} sh -s <<EOF
chown $(id -u):$(id -g) ${BUILD_DIR}/*.dol
cp -a ${BUILD_DIR}/*.dol /paintown-bin/dkp-bin
EOF

################## NO SDL2 libs #########################

#echo "Building 3DS..."
#docker build -t ${ARM_IMAGE} -f docker/Dockerfile.dkp.arm .
#docker run --rm -iv${PWD}:/paintown-bin ${ARM_IMAGE} sh -s <<EOF
#chown $(id -u):$(id -g) ${BUILD_DIR}/*.dol
#cp -a ${BUILD_DIR}/*.dol /paintown-bin/dkp-bin
#EOF

echo "Building Switch..."
docker build -t ${A64_IMAGE} -f docker/Dockerfile.dkp.a64 .
docker run --rm -iv${PWD}:/paintown-bin ${A64_IMAGE} sh -s <<EOF
#chown $(id -u):$(id -g) ${BUILD_DIR}/paintown-switch.nso
#cp -a ${BUILD_DIR}/paintown-switch.nso /paintown-bin/dkp-bin
EOF

echo "
Builds Complete.
"
