#!/bin/bash

EXEDIR=`pwd`
EXE=paintown

# inside tmp
cd `mktemp -d`

# copy executable
cp $EXEDIR/$EXE .

echo "Before"
ldd $EXE

# grab all shared libraries
ALL_EXE_SHARED_LIBRARIES=`ldd $EXE | awk '/=>/ {print $3}' | grep '^/' | uniq | grep SDL`

# for each dep change from rpath to executable_path
while IFS= read -r dylibpath; do

    dylibpath_no_rpath=`echo $dylibpath | sed 's/@rpath\///'`
    dylibname=`basename $dylibpath_no_rpath`

    # copying $dylibname
    cp $dylibpath_no_rpath .

    # changing $dylibname
    patchelf --replace-needed $dylibname "./$dylibname" $EXE

done <<< "$ALL_EXE_SHARED_LIBRARIES"

echo "After"
ldd $EXE
file $EXE

# launcher
echo '#!/bin/bash

if [ ! -d data ]; then
    DATA_VERSION=3.6.0
    DATA_URL="https://github.com/kazzmir/paintown/releases/download/v$DATA_VERSION/data-$DATA_VERSION.zip"
    curl -sSL $DATA_URL -o data.zip
    unzip -q data.zip
    rm data.zip
    mv data-$DATA_VERSION data
fi

./paintown' > run.sh
chmod +x run.sh

# packaging 
ARCH=`uname -m`
OS=`uname -s | tr '[:upper:]' '[:lower:]'`
tar -czf $EXEDIR/$EXE-$OS-$ARCH.tar.gz .

# appimage
echo This script uses 'sudo' to install packages. 'sudo' temporarily elevates
echo your priveleges so that new packages can be installed on your system.
echo When prompted for a password type the password you use to login.

# Dep
sudo apt update -y && sudo apt install tree fuse -y

# Setup
APPDIR=paintown.AppDir
mkdir -p $APPDIR/usr/bin $APPDIR/usr/lib
cp paintown run.sh $APPDIR/usr/bin
cp lib* $APPDIR/usr/lib
cp $EXEDIR/misc/icon.png $APPDIR/paintown.png
cd $APPDIR
ln -s usr/bin/run.sh AppRun
cd ..
echo '[Desktop Entry]
Type=Application
Terminal=true
Name=Paintown
Exec=run.sh
Categories=Game;
Icon=paintown
' > $APPDIR/paintown.desktop
tree $APPDIR

# builder
wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage"
chmod a+x appimagetool-$ARCH.AppImage

# build AppImage
./appimagetool-$ARCH.AppImage $APPDIR paintown-$ARCH.AppImage

# executable
chmod a+x paintown-$ARCH.AppImage
cp paintown-$ARCH.AppImage $EXEDIR