#!/bin/bash -e

docker build -t paintown-steam-build -f docker/Dockerfile.steam .
mkdir -p ${PWD}/steam-bin
docker run --rm -iv${PWD}:/paintown-bin paintown-steam-build sh -s <<EOF
chown $(id -u):$(id -g) /build/build-steam/paintown
cp -a /build/build-steam/paintown /paintown-bin/steam-bin
if [ -z /build/build-steam/src/test ]; then
    find /build/build-steam/src/test -type f -name \*.exe -exec sh -c "chown $(id -u):$(id -g) {}; cp -a {} /paintown-bin/steam-bin" \;
fi
EOF