#!/bin/bash

EXEDIR=`pwd`
EXE=paintown.exe

# inside tmp
cd `mktemp -d`

# copy executable
cp $EXEDIR/mingw-bin/$EXE .
# deps
cp $EXEDIR/misc/dlls/zlib1.dll .

# launcher
echo '
if (-not (Test-Path -Path data)) {
    Invoke-WebRequest -Uri "https://github.com/kazzmir/paintown/releases/download/v3.6.0/data-3.6.0.zip" -OutFile "data.zip"
    Expand-Archive -Path "data.zip" -DestinationPath .
    Remove-Item -Path data.zip
    Rename-Item -Path data-3.6.0 -NewName data
}
Start-Process -FilePath paintown.exe
' > paintown.ps1
echo '
powershell.exe -ExecutionPolicy Bypass -File paintown.ps1
' > run.bat

# packaging 
ARCH=`file paintown.exe | grep -o -E 'x86[_-]64|i[[:digit:]]86|ARM'`
OS=windows
zip -r $EXEDIR/$EXE-$OS-$ARCH.zip .