#!/bin/sh

# If you are trying to compile Paintown from source but have no idea what to do
# try running this script. It will attempt to install all the dependencies you
# need and compile Paintown.

echo This script uses 'sudo' to install packages. 'sudo' temporarily elevates
echo your priveleges so that new packages can be installed on your system.
echo When prompted for a password type the password you use to login.

sudo apt-get install scons liballegro-dev libpng12-dev libfreetype6-dev g++ zlib1g-dev
make

ls -l paintown
echo "Here is the executable. To run it type: ./paintown"
