#!/bin/sh

# If you are trying to compile Paintown from source but have no idea what to do
# try running this script. It will attempt to install all the dependencies you
# need and compile Paintown.

echo This script uses 'sudo' to install packages. 'sudo' temporarily elevates
echo your priveleges so that new packages can be installed on your system.
echo When prompted for a password type the password you use to login.

cd editor && ./gradlew build && cp build/libs/editor.jar .

ls -l *.jar
echo "Here is the executable. To run it type: cd editor && ./run.sh"
