#!/usr/bin/env python

# GTK or QT based installer

# Copy files to some directory, symlink the binary.

import sys

from PyQt4 import QtCore, QtGui, uic
from PyQt4.QtCore import *
from PyQt4.QtGui import *

app = QtGui.QApplication(sys.argv)

# Set the look and feel
QtGui.QApplication.setStyle(QtGui.QStyleFactory.create("Cleanlooks"))

# Load the installer widgets dynamically
currentPage = [0]
eula = [False]
widget = uic.loadUi("installer/installer.ui")

#Back function
def backButton():
    currentPage[0] -= 1
    if currentPage[0] < 0:
        currentPage[0] = 0
    widget.stackedWidget.setCurrentIndex(currentPage[0])

#Forward function
def forwardButton():
    currentPage[0] += 1
    if currentPage[0] > 1 and not eula[0]:
        currentPage[0] = 1
    if currentPage[0] > 4:
        currentPage[0] = 4
    widget.stackedWidget.setCurrentIndex(currentPage[0])

#Set User agreement
def toggleEula():
    eula[0] = not eula[0]

# Update the widgets with the needed Info
widget.connect(widget.back, SIGNAL("clicked()"), backButton)
widget.connect(widget.next, SIGNAL("clicked()"), forwardButton)
widget.connect(widget.eula, SIGNAL("clicked()"), toggleEula)

# Exit installer
exit = QtGui.QAction('Exit', widget)
exit.setShortcut('Ctrl+Q')
exit.setStatusTip('Exit application')
widget.connect(exit, SIGNAL('triggered()'), SLOT('close()'))
widget.file.addAction(exit)

# Page 1 - Intro and graphic
scene = QGraphicsScene()
scene.addPixmap(QPixmap('data/menu/paintown.png'))
widget.WelcomePage.setScene(scene)
widget.WelcomePage.scale(1.15,.94)

# Page 2 - End User Agreement or License
widget.textBrowser.setPlainText(QString(open(str('LICENSE')).read()))
widget.textBrowser.selectAll()
widget.textBrowser.setAlignment(Qt.AlignCenter)
widget.textBrowser.moveCursor(QTextCursor.Start)

# Page 3 - Install Locations

# Page 4 - Console Output

# Page 5 - Finished

# show widget
widget.show()

# Run
app.exec_()


