Import('use')

all = []
def_peg = use.Peg('def.peg')
air_peg = use.Peg('air.peg')
cmd_peg = use.Peg('cmd.peg')
# Serialize peg creation to avoid some race condition
use.Depends(air_peg, def_peg)
use.Depends(cmd_peg, air_peg)
all.append(def_peg)
all.append(air_peg)
all.append(cmd_peg)

for x in all:
    use.Depends(x, 'peg.py')
    use.Depends(x, 'cpp_generator.py')
