Import('use')

testEnv = use.Clone()
testEnv.VariantDir('test', '../../')
testEnv.VariantDir('common', '../common')

testEnv.Append(CPPDEFINES = ['HAVE_NETWORKING'])

source = Split("""test.cpp test/factory/font_factory.cpp""")

env = testEnv
# testEnv.Append(LIBS = [testEnv.SConscript('test/util/network/hawknl/SConscript', exports = ['env'])])

x = []
test = testEnv.Program('network', source)
x.extend(test)
use.AddPostAction(test, use['PAINTOWN_TEST'])
Return('x')
