Import('use')

testEnv = use.Clone()
# testEnv.VariantDir('test', '../../', duplicate = False)
testEnv.VariantDir('test', '../../')

use = testEnv

# SConscript('../../mugen/SConscript', exports = ['use'], variant_dir = 'mugen')
# SConscript('../../paintown-engine/SConscript', exports = ['use'], variant_dir = 'paintown')
# use.Append(LIBS = ['mugen', 'paintown-engine'])

source = Split("""
test.cpp
test/globals.cpp
test/mugen/ast/ast.cpp
test/openbor/pack-reader.cpp
test/openbor/util.cpp
test/openbor/mod.cpp
test/factory/font_render.cpp
test/asteroids/game.cpp
test/factory/collector.cpp
""")

source.append(use.Peg('test/openbor/data.peg'))

x = []
menu_test = testEnv.Program('menu', source)
x.extend(menu_test)
use.AddPostAction(menu_test, use['PAINTOWN_TEST'])
# x.append(testEnv.Program('load-stage', stage_source))
Return('x')
