Import('use')

source = Split("""
sflbits.c
sflcomp.c
sflcons.c
sflconv.c
sflcryp.c
sflcvbs.c
sflcvdp.c
sflcvds.c
sflcvns.c
sflcvsb.c
sflcvsd.c
sflcvsn.c
sflcvtp.c
sflcvts.c
sfldbio.c
sfldir.c
sflenv.c
sflexdr.c
sflfile.c
sflfind.c
sflfort.c
sflhttp.c
sflini.c
sfllang.c
sfllbuf.c
sfllist.c
sflmail.c
sflmath.c
sflmem.c
sflmesg.c
sflmime.c
sflnode.c
sflprint.c
sflslot.c
sflstr.c
sflsymb.c
sflsyst.c
sfltok.c
sfltree.c
sfltron.c
sflxml.c
sfluid.c
sfldate.c
""")

ignored = Split("""
sflcvst.c
sflxmll.c
sflproc.c
sflsock.c
sflmysql.c
""")

x = use.StaticLibrary('sfl', source)
Return('x')
