Import('use')

testEnv = use.Clone()
testEnv.VariantDir('test', '../../')

source = Split("""
test/globals.cpp
test/factory/font_render.cpp
""")

hq2x_source = Split("""hq2x.cpp""")
xbr_source = Split("""xbr.cpp""")
performance_source = Split("""performance.cpp""")

x = []
x.extend(testEnv.Program('hqx', hq2x_source + source))
x.extend(testEnv.Program('xbr', xbr_source + source))
x.extend(testEnv.Program('performance', performance_source + source))
Return('x')
