Import('use')

source = Split("""
test.cpp
../../util/token.cpp
../../util/tokenreader.cpp
../../util/token_exception.cpp
../../util/exceptions/exception.cpp
""")

parse_source = Split("""
parse.cpp
../../util/token.cpp
../../util/tokenreader.cpp
../../util/token_exception.cpp
../../util/exceptions/exception.cpp
../../util/debug.cpp
""")

x = []
token_test = use.Program('test', source)
x.append(token_test)
x.append(use.Program('parse', parse_source))
use.AddPostAction(token_test, use['PAINTOWN_TEST'])
Return('x')
