Import('use')

source = Split("""
test.cpp
../../util/token.cpp
../../util/tokenreader.cpp
../../util/token_exception.cpp
../../exceptions/exception.cpp
""")

x = []
x.append(use.Program('test', source))
Return('x')
