Import('use')

testEnv = use.Clone()
testEnv.VariantDir('test', '../../')
testEnv.VariantDir('common', '../common')

more_source = []
def addObjects(files):
    more_source.extend(files)

use = testEnv
SConscript('../../mugen/parser/SConstruct', exports = ['use', 'addObjects'], variant_dir = 'test-parser')

most_game_source = Split("""
test/mugen/character.cpp
test/mugen/helper.cpp
test/mugen/evaluator.cpp
test/mugen/compiler.cpp
test/mugen/state-controller.cpp
test/mugen/stage.cpp
test/mugen/sprite.cpp
test/mugen/sound.cpp
test/mugen/exception.cpp
test/mugen/util.cpp
test/mugen/animation.cpp
test/mugen/item-content.cpp
test/mugen/item.cpp
test/mugen/command.cpp
test/mugen/background.cpp
test/mugen/parse-cache.cpp
test/gui/rectarea.cpp
test-parser/air.cpp
test-parser/def.cpp
test-parser/cmd.cpp
test/object/alliance.cpp
test/object/object.cpp
test/object/object_attack.cpp
test/paintown-engine/script/script.cpp
test/mugen/ast/ast.cpp
test/globals.cpp
test/configuration.cpp
test/factory/font_render.cpp
test/factory/font_factory.cpp
test/paintown-engine/game/world.cpp
test/mugen/config.cpp
test/mugen/characterhud.cpp
test/mugen/behavior.cpp
test/gui/fadetool.cpp
test/mugen/font.cpp
test/mugen/reader.cpp
test/mugen/section.cpp

""")

load_source = Split("""
load.cpp
common/init.cpp
""")

stage_source = Split("""
load-stage.cpp
common/init.cpp
test/mugen/stage.cpp
test/mugen/character.cpp
test/mugen/helper.cpp
test/mugen/evaluator.cpp
test/mugen/compiler.cpp
test/mugen/sprite.cpp
test/mugen/state-controller.cpp
test/mugen/font.cpp
test/mugen/sound.cpp
test/mugen/exception.cpp
test/mugen/util.cpp
test/mugen/animation.cpp
test/mugen/background.cpp
test/mugen/item-content.cpp
test/mugen/item.cpp
test/mugen/parse-cache.cpp
test/mugen/characterhud.cpp
test/gui/rectarea.cpp
test-parser/air.cpp
test-parser/def.cpp
test-parser/cmd.cpp
test/factory/collector.cpp
test/paintown-engine/factory/shadow.cpp
test/paintown-engine/factory/object_factory.cpp
test/paintown-engine/factory/heart_factory.cpp
test/paintown-engine/game/nameplacer.cpp
test/paintown-engine/game/mod.cpp
test/paintown-engine/level/utils.cpp
test/paintown-engine/game/select_player.cpp
test/paintown-engine/game/character-select.cpp
test/loading.cpp
test/openbor/mod.cpp
test/openbor/util.cpp
test/openbor/pack-reader.cpp
test/paintown-engine/object/item.cpp
test/paintown-engine/object/attack.cpp
test/paintown-engine/object/projectile.cpp
test/paintown-engine/object/animation_event.cpp
test/paintown-engine/object/animation_trail.cpp
test/paintown-engine/object/animation.cpp
test/paintown-engine/object/gib.cpp
test/paintown-engine/object/cat.cpp
test/paintown-engine/object/alliance.cpp
test/paintown-engine/object/actor.cpp
test/paintown-engine/object/object_nonattack.cpp
test/paintown-engine/object/enemy.cpp
test/paintown-engine/object/draw-effect.cpp
test/paintown-engine/object/character.cpp
test/paintown-engine/object/display_character.cpp
test/paintown-engine/object/heart.cpp
test/paintown-engine/object/stimulation.cpp
test/paintown-engine/object/object.cpp
test/paintown-engine/object/object_attack.cpp
test/paintown-engine/object/network_player.cpp
test/paintown-engine/object/network_character.cpp
test/mugen/ast/ast.cpp
test/paintown-engine/script/script.cpp
test/globals.cpp
test/configuration.cpp
test/paintown-engine/game/world.cpp
test/factory/font_render.cpp
test/factory/font_factory.cpp
test/mugen/config.cpp
test/mugen/behavior.cpp
test/gui/fadetool.cpp
test/mugen/reader.cpp
test/mugen/command.cpp
test/mugen/section.cpp
""")

full_source = most_game_source + Split("""
load-full.cpp
common/init.cpp
test/factory/collector.cpp
test/paintown-engine/factory/shadow.cpp
test/paintown-engine/factory/object_factory.cpp
test/paintown-engine/factory/heart_factory.cpp
test/paintown-engine/object/item.cpp
test/paintown-engine/object/attack.cpp
test/paintown-engine/object/projectile.cpp
test/paintown-engine/object/animation_event.cpp
test/paintown-engine/object/animation_trail.cpp
test/paintown-engine/object/animation.cpp
test/paintown-engine/object/gib.cpp
test/paintown-engine/object/cat.cpp
test/paintown-engine/object/alliance.cpp
test/paintown-engine/object/actor.cpp
test/paintown-engine/object/object_nonattack.cpp
test/paintown-engine/object/enemy.cpp
test/paintown-engine/game/select_player.cpp
test/paintown-engine/game/character-select.cpp
test/openbor/util.cpp
test/openbor/pack-reader.cpp
test/openbor/mod.cpp
test/paintown-engine/level/utils.cpp
test/paintown-engine/object/draw-effect.cpp
test/paintown-engine/object/character.cpp
test/paintown-engine/object/display_character.cpp
test/paintown-engine/object/heart.cpp
test/paintown-engine/game/mod.cpp
test/paintown-engine/object/stimulation.cpp
test/paintown-engine/object/network_player.cpp
test/paintown-engine/object/network_character.cpp
test/paintown-engine/game/nameplacer.cpp
""")

stage_source.append(testEnv.Peg('test/openbor/data.peg'))
full_source.append(testEnv.Peg('test/openbor/data.peg'))

ast_source = Split("""
test-parser/air.cpp
test-parser/def.cpp
test-parser/cmd.cpp
test/mugen/exception.cpp
test/mugen/ast/ast.cpp
""")

load_source = Split("""
common/init.cpp
load.cpp
test/globals.cpp
test/factory/font_factory.cpp
test/factory/font_render.cpp
test/paintown-engine/object/draw-effect.cpp
test/paintown-engine/object/gib.cpp
test/paintown-engine/object/object.cpp
test/paintown-engine/object/object_attack.cpp
test/paintown-engine/object/character.cpp
test/paintown-engine/object/player.cpp
test/paintown-engine/script/script.cpp
test/paintown-engine/factory/shadow.cpp
test/paintown-engine/game/select_player.cpp
test/paintown-engine/game/character-select.cpp
test/paintown-engine/object/object_nonattack.cpp
test/mugen/parse-cache.cpp
test/mugen/ast/ast.cpp
test/mugen/sound.cpp
test/mugen/item-content.cpp
test/mugen/item.cpp
test/mugen/animation.cpp
test/mugen/sprite.cpp
test/mugen/util.cpp
test/mugen/config.cpp
test/paintown-engine/object/stimulation.cpp
test/paintown-engine/object/item.cpp
test/paintown-engine/object/network_player.cpp
test/paintown-engine/object/network_character.cpp
test/paintown-engine/object/actor.cpp
test/paintown-engine/object/enemy.cpp
test/paintown-engine/object/cat.cpp
test/paintown-engine/object/alliance.cpp
test/paintown-engine/object/heart.cpp
test/paintown-engine/factory/object_factory.cpp
test/paintown-engine/factory/heart_factory.cpp
test/factory/collector.cpp
test/paintown-engine/object/display_character.cpp
test/mugen/exception.cpp
test/paintown-engine/object/player-common.cpp
test/paintown-engine/game/nameplacer.cpp
test/paintown-engine/object/animation.cpp
test/paintown-engine/object/animation_trail.cpp
test/configuration.cpp
test/paintown-engine/level/utils.cpp
test/paintown-engine/level/blockobject.cpp
test/openbor/mod.cpp
test/openbor/pack-reader.cpp
test/paintown-engine/game/mod.cpp
test/openbor/util.cpp
test/paintown-engine/object/attack.cpp
test/paintown-engine/object/projectile.cpp
test/paintown-engine/object/animation_event.cpp
test-parser/air.cpp
test-parser/def.cpp
test-parser/cmd.cpp
""")

load_source.append(testEnv.Peg('test/openbor/data.peg'))

source = Split("""
common/init.cpp
common/timer.cpp
test/configuration.cpp
test/globals.cpp
test/factory/font_factory.cpp
test/factory/font_render.cpp
""")

character_select_source = Split("""
test/paintown-engine/game/character-select.cpp
select-main.cpp
test/mugen/exception.cpp
test/openbor/mod.cpp
test/openbor/pack-reader.cpp
test/openbor/util.cpp
test/paintown-engine/game/mod.cpp
test/paintown-engine/game/nameplacer.cpp
test/paintown-engine/game/select_player.cpp
test/paintown-engine/level/utils.cpp
test/paintown-engine/object/animation.cpp
test/paintown-engine/object/animation_event.cpp
test/paintown-engine/object/animation_trail.cpp
test/paintown-engine/object/attack.cpp
test/paintown-engine/object/character.cpp
test/paintown-engine/object/display_character.cpp
test/paintown-engine/object/draw-effect.cpp
test/paintown-engine/object/effect.cpp
test/paintown-engine/object/gib.cpp
test/paintown-engine/object/object.cpp
test/paintown-engine/object/object_attack.cpp
test/paintown-engine/object/object_nonattack.cpp
test/paintown-engine/object/player.cpp
test/paintown-engine/object/player-common.cpp
test/paintown-engine/object/projectile.cpp
test/paintown-engine/object/alliance.cpp
test/paintown-engine/script/script.cpp
""")

game_source = Split("""
common/init.cpp
game.cpp
test/globals.cpp
test/factory/font_factory.cpp
test/factory/font_render.cpp
test/paintown-engine/object/draw-effect.cpp
test/paintown-engine/object/gib.cpp
test/paintown-engine/object/object.cpp
test/paintown-engine/object/object_attack.cpp
test/paintown-engine/object/character.cpp
test/paintown-engine/object/player.cpp
test/paintown-engine/script/script.cpp
test/paintown-engine/factory/shadow.cpp
test/paintown-engine/game/select_player.cpp
test/paintown-engine/game/character-select.cpp
test/paintown-engine/object/object_nonattack.cpp
test/mugen/parse-cache.cpp
test/mugen/ast/ast.cpp
test/mugen/sound.cpp
test/mugen/item-content.cpp
test/mugen/item.cpp
test/mugen/animation.cpp
test/mugen/sprite.cpp
test/mugen/util.cpp
test/mugen/config.cpp
test/paintown-engine/object/stimulation.cpp
test/paintown-engine/object/item.cpp
test/paintown-engine/object/network_player.cpp
test/paintown-engine/object/network_character.cpp
test/paintown-engine/object/actor.cpp
test/paintown-engine/object/alliance.cpp
test/paintown-engine/object/enemy.cpp
test/paintown-engine/object/cat.cpp
test/paintown-engine/object/heart.cpp
test/paintown-engine/factory/object_factory.cpp
test/paintown-engine/factory/heart_factory.cpp
test/factory/collector.cpp
test/paintown-engine/object/display_character.cpp
test/paintown-engine/object/effect.cpp
test/mugen/exception.cpp
test/paintown-engine/object/player-common.cpp
test/paintown-engine/game/nameplacer.cpp
test/paintown-engine/object/animation.cpp
test/paintown-engine/object/animation_trail.cpp
test/configuration.cpp
test/paintown-engine/environment/atmosphere.cpp
test/paintown-engine/trigger/trigger.cpp
test/paintown-engine/level/scene.cpp
test/paintown-engine/level/block.cpp
test/paintown-engine/level/blockobject.cpp
test/paintown-engine/level/random-scene.cpp
test/paintown-engine/level/utils.cpp
test/paintown-engine/level/cacher.cpp
test/openbor/mod.cpp
test/openbor/pack-reader.cpp
test/paintown-engine/game/mod.cpp
test/paintown-engine/game/adventure_world.cpp
test/paintown-engine/game/world.cpp
test/openbor/util.cpp
test/paintown-engine/object/attack.cpp
test/paintown-engine/object/projectile.cpp
test/paintown-engine/object/animation_event.cpp
test-parser/air.cpp
test-parser/def.cpp
test-parser/cmd.cpp
""")

game_source.append(testEnv.Peg('test/openbor/data.peg'))

x = []
def makeTest(name, files):
    test = testEnv.Program(name, files)
    x.append(test)
    testEnv.AddPostAction(test, testEnv['PAINTOWN_TEST'])

makeTest('load', load_source)
makeTest('game', game_source)

# Character select test
character_select = testEnv.Program('character-select', source + character_select_source + testEnv.Peg('test/openbor/data.peg'))
x.append(character_select)

# x.append(testEnv.Program('load', load_source + most_game_source))
#makeTest('load-full', full_source)
#makeTest('load', load_source + most_game_source)
#makeTest('serialize', ['serialize.cpp'] + ast_source)
#x.append(testEnv.Program('load-stage', stage_source))
#x.append(testEnv.Program('palette', ['palette.cpp', 'test/debug.cpp']))
Return('x')
