all:
	./gradlew build

clean:
	./gradlew clean

animator:
	java -classpath build/libs/editor.jar com.rafkind.paintown.animator.Animator2

platformer:
	java -classpath build/libs/editor.jar com.rafkind.platformer.MapEditor
