Import('use')

testEnv = use.Clone()

testEnv.VariantDir('test', '../../', duplicate = False)

source = Split("""file-system.cpp""")

x = []
def makeTest(name, files):
    test = testEnv.Program(name, files)
    x.extend(test)
    testEnv.AddPostAction(test, testEnv['PAINTOWN_TEST'])

makeTest('file-system', source)
x.extend(testEnv.Program('loading', ['loading.cpp']))

Return('x')
