Import('use')

source = Split("""
file-system.cpp
../../util/file-system.cpp
../../util/exceptions/exception.cpp
../../util/thread.cpp
../../util/debug.cpp
../../util/system.cpp
""")

x = []
test = use.Program('test', source)
use.AddPostAction(test, use['PAINTOWN_TEST'])
x.append(test)
Return('x')
