# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
  end
  
  # Other directories 
  config.vm.synced_folder "../../../", "/home/vagrant/paintown", type: "nfs"
  config.nfs.map_uid = Process.uid
  config.nfs.map_gid = Process.gid

  # Update chef
  config.vm.provision :shell, :inline => "sudo true && apt-get update && curl -L https://www.opscode.com/chef/install.sh | sudo bash"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef-cookbooks"
    chef.add_recipe "android"
  end
end
