# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "squeeze32-vanilla"
  config.vm.box_url = "https://dl.dropbox.com/u/2289657/squeeze32-vanilla.box"
  config.vm.network :hostonly, "192.168.33.10"
  config.vm.customize ["modifyvm", :id, "--memory", 512]
  # config.vm.network :bridged
  # config.vm.forward_port 80, 8080
  
  # Other directories
  config.vm.share_folder("paintown", "/home/vagrant/paintown", "../../../", :nfs => (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)) 
  
  # Update chef
  config.vm.provision :shell, :inline => "sudo true && apt-get update && curl -L https://www.opscode.com/chef/install.sh | sudo bash"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef-cookbooks"
    chef.add_recipe "android"
  end
end
