#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
EXEDIR="$SCRIPT_DIR/.." 
EXE=paintown

# inside tmp
cd $SCRIPT_DIR
rm -rf tmp && mkdir tmp && cd tmp

# Setup
APPDIR=paintown.AppDir
mkdir -p $APPDIR/usr/bin $APPDIR/usr/lib
cp $EXEDIR/paintown $APPDIR/usr/bin
cp $EXEDIR/misc/icon.png $APPDIR/paintown.png
#cp $EXEDIR/lib* $APPDIR/usr/lib
cd $APPDIR
ln -s usr/bin/paintown AppRun
cd ..
echo '[Desktop Entry]
Type=Application
Terminal=true
Name=Paintown
Exec=paintown %U
Categories=Game;
Icon=paintown
' > $APPDIR/paintown.desktop

echo "Before"
ldd $APPDIR/usr/bin/$EXE

# grab all shared libraries
ALL_EXE_SHARED_LIBRARIES=`ldd $APPDIR/usr/bin/$EXE | awk '/=>/ {print $3}' | grep '^/' | uniq | grep SDL`

# for each dep change from rpath to executable_path
while IFS= read -r dylibpath; do

    dylibpath_no_rpath=`echo $dylibpath | sed 's/@rpath\///'`
    dylibname=`basename $dylibpath_no_rpath`

    # copying $dylibname
    cp $dylibpath_no_rpath $APPDIR/usr/lib

    # changing $dylibname
    patchelf --replace-needed $dylibpath "\$ORIGIN/../lib/$dylibname"  $APPDIR/usr/bin/$EXE

done <<< "$ALL_EXE_SHARED_LIBRARIES"

echo "After"
ldd $APPDIR/usr/bin/$EXE
file $APPDIR/usr/bin/$EXE

# builder
echo This script uses 'sudo' to install packages. 'sudo' temporarily elevates
echo your priveleges so that new packages can be installed on your system.
echo When prompted for a password type the password you use to login.

# Dep fuse required
sudo apt update -yqq && sudo apt install tree fuse -yqq

ARCH=`uname -m`
wget -q "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage"
chmod a+x appimagetool-$ARCH.AppImage

# build AppImage
./appimagetool-$ARCH.AppImage $APPDIR paintown-$ARCH.AppImage

# executable
chmod a+x paintown-$ARCH.AppImage
cp paintown-$ARCH.AppImage $EXEDIR

# Tree
tree $APPDIR
