#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
EXEDIR="$SCRIPT_DIR/.." 
EXE=paintown

# inside tmp
cd $SCRIPT_DIR
rm -rf tmp && mkdir tmp && cd tmp

# copy executable
cp $EXEDIR/steam-bin/$EXE .
# Copy launcher
cp $EXEDIR/misc/steam/steam-run.sh .
mkdir controller_config
cp $EXEDIR/misc/steam/paintown\ keyboard\ layout_0.vdf controller_config

# packaging 
ARCH=x86-64
OS=linux-steam
zip -r $EXEDIR/$EXE-$OS-$ARCH.zip .