#!/bin/bash -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
EXEDIR="$SCRIPT_DIR/.." 
EXE=paintown.pkg

APPVERSION_TAG=`git tag --sort=-committerdate | head -n 1`
APPVERSION_COMMIT=`git log --format=%h -n 1`

# Regular expression to match 'v' followed by a number version
TAG_VERSION_REGEX='^v[0-9]+\.[0-9]+'

# Check if the variable matches the regular expression
if [[ $APPVERSION_TAG =~ $TAG_VERSION_REGEX ]]; then
    APPVERSION=$APPVERSION_TAG
else
    APPVERSION=$APPVERSION_COMMIT
fi

# inside tmp
cd $SCRIPT_DIR
rm -rf tmp && mkdir tmp && cd tmp

# copy resources
cp $EXEDIR/misc/psp/ICON0.PNG $EXEDIR/misc/psp/ICON1.PNG .
cp $EXEDIR/misc/psp/PIC0.PNG $EXEDIR/misc/psp/PIC1.PNG .
cp $EXEDIR/misc/psp/SND0.AT3 .
cp $EXEDIR/paintown-psp.elf .
cp -r $EXEDIR/data DATA.PSAR

# builder
docker run --rm -iv `pwd`:/paintown-bin -w /paintown-bin paintown-psp-build bash -s <<EOF

# for creating PARAM.SFO files.
mksfo "Paintown" PARAM.SFO

# for fixing up import tables post-linking to remove unused functions from the executable.
psp-fixup-imports paintown-psp.elf

# for converting specially made ELFs to PRX files.
psp-prxgen paintown-psp.elf paintown-psp.prx

# pack-pbp <output.pbp> <param.sfo> <icon0.png> <icon1.pmf> <pic0.png> <pic1.png> <snd0.at3> <data.psp> <data.psar>
# <output.pbp>: The desired name for your PBP file.
# <param.sfo> : The PARAM.SFO file containing metadata about your application.
# <icon0.png> : The icon image that represents your application on the PSP menu.
# <icon1.pmf> : The 44x44 pixel image file.
# <pic0.png>  : The background image for the PSP menu. (PSP menu background): 480x272 pixels
# <pic1.png>  : The background image for the settings screen.  (Settings screen background): 480x272 pixels
# <snd0.at3>  : The startup sound file.
# <data.psp>  : The main executable file (EBOOT.BIN).
# <data.psar> : An optional data file in PSAR format.

# PBP
pack-pbp EBOOT.PBP PARAM.SFO ICON0.PNG ICON1.PNG PIC0.PNG PIC1.PNG SND0.AT3 paintown-psp.elf DATA.PSAR

EOF

tree

# Move to root
mv EBOOT.PBP $EXEDIR/paintown-psp-$APPVERSION.pbp