# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "centos63"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
  config.vm.network :hostonly, "192.168.33.10"
  # config.vm.network :bridged
  config.vm.forward_port 80, 8080
  
  # Other directories
  config.vm.share_folder "paintown-www", "/home/vagrant/paintown", "./www", :create => true
  
  # Update chef (To support latest cookbooks)
  config.vm.provision :shell, :inline => "sudo true && curl -L https://www.opscode.com/chef/install.sh | sudo bash"

  config.vm.provision :chef_solo do |chef|
    # Site information
    chef.json = {
        "mysql" => {
            "server_root_password" => "paintown",
            "server_repl_password" => "paintown",
            "server_debian_password" => "paintown",
            "bind_address" => "127.0.0.1"
        },
        "apache" => {
            "default_site_enabled" => true
        }
    }
    
=begin
        # If you want to make commit edits add this to the named file below
        "paintown" => {
            "username" => '',
            "password" => ''
        }
=end
    if File.exist?('./svn-info')
        chef.json.add IO.read('./svn-info')
    end
    
    chef.cookbooks_path = "../chef-cookbooks"
    chef.add_recipe "yum"
    chef.add_recipe "build-essential"
    chef.add_recipe "vim"
    chef.add_recipe "openssl"
    chef.add_recipe "xml"
    chef.add_recipe "apache2"
    chef.add_recipe "apache2::mod_php5"
    chef.add_recipe "apache2::mod_rewrite"
    chef.add_recipe "mysql"
    chef.add_recipe "mysql::server"
    chef.add_recipe "php"
    chef.add_recipe "php::module_curl"
    chef.add_recipe "php::module_mysql"
    chef.add_recipe "php::module_memcache"
    chef.add_recipe "php::module_sqlite3"
    chef.add_recipe "web"
  end
end
