import os

env = Environment(ENV = os.environ)
#env['CC'] = 'clang'
#env['CXX'] = 'clang++'

def gmeLibrary(env):
    use = env
    return SConscript('../../util/gme/SConscript', exports = ['use'], variant_dir = 'gme')

def zipLibrary(env):
    zipEnv = env.Clone()
    env = zipEnv
    return SConscript('../../util/zip/SConscript', exports = ['env'], variant_dir = 'zip')

def sflLibrary(env):
    sflEnv = env.Clone()
    use = sflEnv
    return SConscript('../../util/sfl/SConscript', exports = ['use'], variant_dir = 'sfl')

def dumbLibrary(env):
    dumbEnv = env.Clone()
    env = dumbEnv
    return SConscript('../../util/dumb/SConscript', exports = ['env'], variant_dir = 'dumb')

def sdlMixerLibrary(env):
    use = env
    return SConscript('../../util/sdl/mixer/SConscript', exports = ['use'], variant_dir = 'mixer')

def isLinux():
    import sys
    return 'linux' in sys.platform

# Just test this on linux for now
if isLinux():
    all = []
    try:
        env.VariantDir('build', '../../')
        env.Append(CPPPATH = ['#/src'])
        source = Split("""test.cpp build/util/music-player.cpp build/util/music-renderer.cpp build/util/debug.cpp
        build/util/audio.cpp build/util/exceptions/exception.cpp build/util/file-system.cpp build/util/directory.cpp build/util/thread.cpp build/util/system.cpp""")
        wav_source = Split("""wav.cpp build/util/audio.cpp build/util/debug.cpp build/util/exceptions/exception.cpp build/util/sound.cpp build/util/load_exception.cpp""")
        music_source = Split("""music.cpp build/music/util/music-player.cpp build/music/util/music-renderer.cpp build/music/util/audio.cpp build/music/util/exceptions/exception.cpp build/music/util/sound.cpp build/music/util/load_exception.cpp build/music/util/debug.cpp build/music/util/music.cpp build/music/util/file-system.cpp build/music/util/directory.cpp build/music/util/thread.cpp build/music/util/system.cpp""")

        env.Append(CPPPATH = '../..')
        env.Append(CPPDEFINES = ['USE_SDL', 'HAVE_MP3_MPG123', 'HAVE_OGG'])
        env.Append(CCFLAGS = ['-g3'])
        #env.Append(CCFLAGS = ['-O2', '-pg'])
        #env.Append(LINKFLAGS = ['-pg'])
        # env.ParseConfig('sdl-config --libs --cflags')
        env.ParseConfig('sdl-config --libs --cflags')
        env.ParseConfig('pkg-config vorbis vorbisfile --libs')

        env.Append(LIBS = ['mpg123', gmeLibrary(env), dumbLibrary(env), sdlMixerLibrary(env), sflLibrary(env), zipLibrary(env), 'z'])

        musicEnv = env.Clone()
        musicEnv.VariantDir('build/music', '../../')
        #musicEnv.Append(CPPDEFINES = ['HAVE_OGG'])
        #musicEnv.ParseConfig('pkg-config vorbis vorbisfile --libs')
        # musicEnv.Append(LIBS = [zipLibrary(env), 'z', sflLibrary(env)])

        program = env.Program('test', source)
        wav = env.Program('wav', wav_source)
        music = musicEnv.Program('music', music_source)
        all.extend(program)
        all.extend(wav)
        all.extend(music)
        # all = [program, wav]
    except OSError:
        print "Problem with music test!: "
    Return('all')
else:
    all = []
    Return('all')
