import os
Import( 'env' )

# env = Environment( ENV = os.environ )

source = Split("""
src/crc.c
src/err.c
src/errorstr.c
src/group.c
src/hthread.c
src/htcondition.c
src/ipx.c
src/loopback.c
src/htmutex.c
src/nl.c
src/nltime.c
src/sock.c
""");

env.Append(CPPPATH = 'hawknl')

x = env.StaticLibrary('hawknl', source)
Return( 'x' )
